PotentialForAfrica/Controllers/CandidatController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PotentialForAfrica.Data;
using PotentialForAfrica.Helpers;
using PotentialForAfrica.Interfaces;
using PotentialForAfrica.Models;
using IEmailSender = PotentialForAfrica.Interfaces.IEmailSender;

namespace PotentialForAfrica.Controllers
{
    public class CandidatController : Controller
    {
        private readonly ICandidatService mCandidatService;
        private readonly IEmailSender mMailSenderService;
        public CandidatController(ICandidatService pCandidatService, IEmailSender emailSender)
        {
            mCandidatService = pCandidatService;
            mMailSenderService = emailSender;
        }

        // GET: Candidat
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await mCandidatService.RecupererCandidatsAsync());
        }
      
        //  GET: Candidat/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Candidat/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CandidatModel candidatModel,IFormFile FileCV)
        {
            if (ModelState.IsValid)
            {
                candidatModel.CVPath = await mCandidatService.UploadCV(FileCV, candidatModel.Nom, candidatModel.Prenom);
                if ( string.IsNullOrWhiteSpace(candidatModel.CVPath))
                {
                    ViewBag.message = "upload de CV est echoué,essayez de nouveau";
                    return View(candidatModel);
                }
                await mCandidatService.AjouterCandidat(candidatModel);
                var message = new Message($"{candidatModel.Nom} {candidatModel.Prenom}",candidatModel.Mail, "Votre Candidature", $"Bonjour {candidatModel.Nom} {candidatModel.Prenom}, vous avez postulé avec succès pour l'offre développeur dotnet");

                // mMailSenderService.SendEmail(message);
                return RedirectToAction(nameof(Create));
            }
            return View(candidatModel);
        }

        // GET: Candidat/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var candidatModel = await mCandidatService.RecupererCandidatsAsyncById(id);
            if (candidatModel == null)
            {
                return NotFound();
            }
            return View(candidatModel);
        }

        // POST: Candidat/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int CandidatId)
        {
            var candidatModel = await mCandidatService.RecupererCandidatsAsyncById(CandidatId);
            if (candidatModel != null)
            {
                await mCandidatService.RemoveCandidatsAsync(candidatModel);
            }
            ViewBag.message = "suppression impossible,Erreur au nivaeu de serveur";
            return RedirectToAction(nameof(Index));
        }

    }
}

PotentialForAfrica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PotentialForAfrica</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PotentialForAfrica.styles.css" asp-append-version="true" />
    <link href="~/datatables/datatables.css" rel="stylesheet" />
    <link href="~/datatables/datatables.min.css" rel="stylesheet" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PotentialForAfrica</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidat" asp-action="Create">Ajouter une candidature</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidat" asp-action="Index">liste des candidatures</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PotentialForAfrica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/datatables/datatables.js"></script>
    <script src="~/datatables/datatables.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>